name: duckpowered
base: core20
version: '0.1a'
summary: Intelligent power savings that don't effect performance.
description: |
  Tweet tweet.
grade: stable
confinement: strict

plugs:
   duckpowered-cpu-control:
     interface: cpu-control
   duckpowered-system-files:
     interface: system-files
     write:
       - /etc/default/grub
   duckpowered-system-observe:
     interface: system-observe
   duckpowered-wayland:
     interface: wayland
   duckpowered-x11:
     interface: x11

apps:
  duckpowered:
    command: usr/bin/run
    plugs:
      - duckpowered-system-files
      - duckpowered-wayland
      - duckpowered-x11
  duckpowered-service:
    command: usr/bin/run start
    plugs:
      - duckpowered-cpu-control
      - duckpowered-system-observe
    daemon: simple    

hooks:
  install:
    plugs:
      - duckpowered-system-files
      - duckpowered-wayland
      - duckpowered-x11
      # the following may not be needed
      - duckpowered-system-observe
  remove:
    plugs:
      - duckpowered-system-files
      # the following may not be needed
      - duckpowered-system-observe
    

parts:
  runscript:
    plugin: dump
    source: .
    override-build: |
      snapcraftctl build
      chmod +x $SNAPCRAFT_PART_INSTALL/duckpowered.sh
      mkdir $SNAPCRAFT_PART_INSTALL/cargo
      mkdir $SNAPCRAFT_PART_INSTALL/cargo/root
      cp /usr/bin/vmstat $SNAPCRAFT_PART_INSTALL/cargo
      cp /usr/bin/getconf $SNAPCRAFT_PART_INSTALL/cargo
      cp /usr/bin/lscpu $SNAPCRAFT_PART_INSTALL/cargo
      apt -y install bc
      duckpowered_bcloc=$(whereis bc | awk '{print $2}')
      cp "$duckpowered_bcloc" $SNAPCRAFT_PART_INSTALL/cargo
      apt -y install apt-utils
      apt -y install kmod
      duckpowered_mploc=$(whereis modprobe | awk '{print $2}')
      cp "$duckpowered_mploc" $SNAPCRAFT_PART_INSTALL/cargo/root
      apt -y install grub-common
      duckpowered_roachloc=$(whereis grub-mkconfig | awk '{print $2}')
      cp "$duckpowered_roachloc" $SNAPCRAFT_PART_INSTALL/cargo/root
      apt -y install zenity
      cp /usr/bin/zenity $SNAPCRAFT_PART_INSTALL/cargo
      
      
    organize:
      duckpowered.sh: usr/bin/run
  install-hook:
      plugin: dump
      source: .
      override-build: |
        snapcraftctl build
        chmod +x $SNAPCRAFT_PART_INSTALL/duckpowered-install-hook.sh
      organize:
        duckpowered-install-hook.sh: snap/hooks/install
  remove-hook:
      plugin: dump
      source: .
      override-build: |
        snapcraftctl build
        chmod +x $SNAPCRAFT_PART_INSTALL/duckpowered-remove-hook.sh
      organize:
        duckpowered-remove-hook.sh: snap/hooks/remove
