name: duckpowered
base: core20
version: '1.1d-norm'
summary: Intelligent power savings that don't effect performance.
description: |
  Tweet tweet.
grade: stable
confinement: strict

# This is the snapcraft.yaml use to generate the ARM64, ARMHF and AMD64 builds. For the PowerPC Builds please see alt/snapcraft-alt.yaml

layout:
  /etc/duckpowered:
     bind: $SNAP_DATA
  /usr/quack/env:
    bind: $SNAP/shipping

plugs:
  cpu-control:
    interface: cpu-control
  system-observe:
     interface: system-observe
  network:
     interface: network
 
 
apps:
  duckpowered:
    command: usr/bin/dashsh
    adapter: none
    plugs:
      - network
  actual-service:
    command: usr/bin/run
    adapter: none
    plugs:
      - cpu-control
      - system-observe
    daemon: simple    

parts:
  actual-service:
    plugin: dump
    source: ./actual-service
    override-build: |
      snapcraftctl build
      mkdir $SNAPCRAFT_PART_INSTALL/shipping
      cp /usr/bin/vmstat $SNAPCRAFT_PART_INSTALL/shipping
      cp /usr/bin/lscpu $SNAPCRAFT_PART_INSTALL/shipping
      cp /usr/bin/awk $SNAPCRAFT_PART_INSTALL/shipping
      cp /bin/cat $SNAPCRAFT_PART_INSTALL/shipping
      cp /usr/bin/tail $SNAPCRAFT_PART_INSTALL/shipping
      cp /usr/bin/tee $SNAPCRAFT_PART_INSTALL/shipping
      cp /bin/grep $SNAPCRAFT_PART_INSTALL/shipping
      apt -y install bash
      cp /bin/bash $SNAPCRAFT_PART_INSTALL/shipping
      chmod +x $SNAPCRAFT_PART_INSTALL/main.sh
      
    organize:
      main.sh: usr/bin/run
      
  gui:
    plugin: dump
    source: ./gui
    stage-packages:
      - libwebkit2gtk-4.0-37
      - libgtk-3-0
      - libappindicator3-1
    override-build: |
      snapcraftctl build
      sudo apt install libwebkit2gtk-4.0-dev build-essential curl wget libssl-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev
      cd $SNAPCRAFT_PART_INSTALL
      chmod +x quacky-build/quacky-manager.sh
      ./quacky-build/quacky-manager.sh
      chmod +x quacky-build/quacky-cleanup.sh
      ./quacky-build/quacky-cleanup.sh
      rm -r quacky-build
    organize:
      duck-powered-dashboard: usr/bin/dash
      actual-gui-launch.sh: usr/bin/dashsh

