name: duckpowered
base: core20
version: '0.1b'
summary: Intelligent power savings that don't effect performance.
description: |
  Tweet tweet.
grade: stable
confinement: strict


layout:
  /usr/bin:
     bind: $SNAP/shipping

plugs:
  cpu-control:
    interface: cpu-control
  kernel-module-load-deny-intel-pstate:
     interface: kernel-module-load
     modules:
       - name: intel_pstate
         load: denied
  system-observe:
     interface: system-observe
 
 
apps:
  duckpowered:
    command: usr/bin/run
    adapter: none
    plugs:
      - cpu-control
      - system-observe
      - kernel-module-load-deny-intel-pstate
  actual-service:
    command: usr/bin/run
    adapter: none
    plugs:
      - cpu-control
      - system-observe
      - kernel-module-load-deny-intel-pstate
    daemon: simple    

parts:
  runscript:
    plugin: dump
    source: .
    override-build: |
      snapcraftctl build
      mkdir $SNAPCRAFT_PART_INSTALL/shipping
      cp /usr/bin/vmstat $SNAPCRAFT_PART_INSTALL/shipping
      cp /usr/bin/lscpu $SNAPCRAFT_PART_INSTALL/shipping
      cp /usr/bin/awk $SNAPCRAFT_PART_INSTALL/shipping
      cp /bin/cat $SNAPCRAFT_PART_INSTALL/shipping
      cp /usr/bin/tail $SNAPCRAFT_PART_INSTALL/shipping
      cp /usr/bin/tee $SNAPCRAFT_PART_INSTALL/shipping
      cp /bin/grep $SNAPCRAFT_PART_INSTALL/shipping
      apt -y install bash
      cp /bin/bash $SNAPCRAFT_PART_INSTALL/shipping
      chmod +x $SNAPCRAFT_PART_INSTALL/actual-service/main.sh
      cp $SNAPCRAFT_PART_INSTALL/actual-service/main.sh $SNAPCRAFT_PART_INSTALL
      
    organize:
      main.sh: usr/bin/run
