name: duckpowered
base: core20
version: '1.1a'
summary: Intelligent power savings that don't effect performance.
description: |
  Tweet tweet.
grade: stable
confinement: strict


layout:
  /etc/duckpowered:
     bind: $SNAP_DATA
  /usr/quack/env:
    bind: $SNAP/shipping

plugs:
  cpu-control:
    interface: cpu-control
  system-observe:
     interface: system-observe
 
 
apps:
  duckpowered:
    extensions: [gnome-3-38]
    command: usr/bin/dash
    adapter: none
  actual-service:
    command: usr/bin/run
    adapter: none
    plugs:
      - cpu-control
      - system-observe
    daemon: simple    

parts:
  actual-service:
    plugin: dump
    source: ./actual-service
    override-build: |
      snapcraftctl build
      mkdir $SNAPCRAFT_PART_INSTALL/shipping
      cp /usr/bin/vmstat $SNAPCRAFT_PART_INSTALL/shipping
      cp /usr/bin/lscpu $SNAPCRAFT_PART_INSTALL/shipping
      cp /usr/bin/awk $SNAPCRAFT_PART_INSTALL/shipping
      cp /bin/cat $SNAPCRAFT_PART_INSTALL/shipping
      cp /usr/bin/tail $SNAPCRAFT_PART_INSTALL/shipping
      cp /usr/bin/tee $SNAPCRAFT_PART_INSTALL/shipping
      cp /bin/grep $SNAPCRAFT_PART_INSTALL/shipping
      apt -y install bash
      cp /bin/bash $SNAPCRAFT_PART_INSTALL/shipping
      chmod +x $SNAPCRAFT_PART_INSTALL/main.sh
      
    organize:
      main.sh: usr/bin/run
      
  gui:
    plugin: dump
    source: ./gui
    override-build: |
      snapcraftctl build
      cd $SNAPCRAFT_PART_INSTALL
      snap install rustup --classic
      rustup install stable
      rustup default stable
      fallocate -l 8G /buildSwapfile
      chmod 600 /buildSwapfile
      mkswap /buildSwapfile
      swapon /buildSwapfile
      cargo install tauri-cli
      apt -y install libssl-dev
      cargo tauri build -b none
      cp ./src-tauri/target/release/duck-powered-dashboard .
      chmod +x ./duck-powered-dashboard
      rm -r ./src-tauri/target
    organize:
      duck-powered-dashboard: usr/bin/dash

