name: duckpowered
base: core20
version: '0.1'
summary: Intelligent power savings that don't effect performance.
description: |
  Tweet tweet.
grade: stable
confinement: classic

apps:
  duckpowered:
    command: usr/bin/run

parts:
  copy-runscript:
    plugin: dump
    source: .
    override-build: |
      snapcraftctl build
      chmod +x $SNAPCRAFT_PART_INSTALL/duckpowered.sh
    organize:
      duckpowered.sh: usr/bin/run
