name: duckpowered
base: core20
version: '0.1'
summary: Intelligent power savings that don't effect performance.
description: |
  Tweet tweet.
grade: stable
confinement: strict

plugs:
   duckpowered-cpu-control:
     interface: cpu-control
   duckpowered-system-files:
     interface: system-files
     write:
       - /etc/default/grub
   duckpowered-system-observe:
     interface: system-observe

apps:
  duckpowered:
    command: usr/bin/run
    plugs:
      - duckpowered-system-files
  duckpowered-service:
    command: usr/bin/run start
    plugs:
      - duckpowered-cpu-control
      - duckpowered-system-observe
    daemon: simple    

parts:
  copy-runscript:
    plugin: dump
    source: .
    override-build: |
      snapcraftctl build
      chmod +x $SNAPCRAFT_PART_INSTALL/duckpowered.sh
      mkdir $SNAPCRAFT_PART_INSTALL/cargo
      mkdir $SNAPCRAFT_PART_INSTALL/cargo/root
      cp /usr/bin/vmstat $SNAPCRAFT_PART_INSTALL/cargo
      cp /usr/bin/getconf $SNAPCRAFT_PART_INSTALL/cargo
      cp /usr/bin/lscpu $SNAPCRAFT_PART_INSTALL/cargo
      apt install bc
      duckpowered_bcloc=$(whereis bc | awk '{print $2}')
      cp "$duckpowered_bcloc" $SNAPCRAFT_PART_INSTALL/cargo
      apt install modprobe
      cp /usr/sbin/modprobe $SNAPCRAFT_PART_INSTALL/cargo/root
      
    organize:
      duckpowered.sh: usr/bin/run
